name: mdc_dart
description: Dart wrapper for the MDC Web vanilla components.
version: 0.0.1-pre
author: Gilyazeev Adel <Atom735.ag47@gmail.com>
homepage: https://github.com/Atom735/mdc_dart

environment:
  sdk: '>=2.9.1 <3.0.0'

dependencies:
  js: ^0.6.2
  meta: ^1.2.2

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
  path: ^1.7.0
  # build_runner: any
  # build_test: any
  # build_web_compilers: any
